# -*- coding: utf-8 -*-
"""John Travolta.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jwK9OaXEawVH5gIQCnvgfCDIB8MlDhJy
"""

nama = input("Nama : ")
jam_kerja = float(input("Total Jam Kerja (per Minggu) : "))
pengeluaran = float(input("Total Pengeluaran (per Minggu) : "))
 
print(f"\nOutput")
print(f"------")

if jam_kerja < 1 or jam_kerja > 168:
  print("Maaf, Total Jam Kerja yang Anda masukan tidak masuk akal")
else:
  if jam_kerja <= 40:
    pemasukan = jam_kerja*15000
    
  elif jam_kerja >= 41:
    pemasukan = 40*15000 + (jam_kerja-40)*15000*3/2

  if pemasukan > pengeluaran:
    print("Pemasukan Anda sebesar Rp.{:.0f}. Anda dapat menabung!".format(pemasukan))
  elif pemasukan == pengeluaran:
      print("Pemasukan Anda sebesar Rp.{:.0f}. Anda tidak dapat menabung!".format(pemasukan))
  else:
        print("Pemasukan Anda sebesar Rp.{:.0f}. Silahkan cari tambahan!".format(pemasukan))